FROM arm64v8/node:lts-alpine3.18

ARG TOKEN
ARG CLIENTID
ARG GUILDID
ARG DATABASE_URL
ARG NEISKEY
ARG GITHUBTOKEN

ENV TOKEN=$TOKEN
ENV CLIENTID=$CLIENTID
ENV GUILDID=$GUILDID
ENV DATABASE_URL=$DATABASE_URL
ENV NEISKEY=$NEISKEY
ENV GITHUBTOKEN=$GITHUBTOKEN

ENV TZ=Asia/Seoul

WORKDIR /usr/app
COPY ./ ./
RUN npm install

CMD ["node", "main.js"]
