FROM arm64v8/node:lts-alpine3.18

ARG TOKEN
ARG CLIENTID
ARG DATABASE_URL
ARG GITHUBTOKEN

ENV TOKEN=$TOKEN
ENV CLIENTID=$CLIENTID
ENV DATABASE_URL=$DATABASE_URL
ENV DATABASE_USER=$DATABASE_USER
ENV DATABASE_PASSWORD=$DATABASE_PASSWORD
ENV DATABASE_PORT=$DATABASE_PORT

ENV GITHUBTOKEN=$GITHUBTOKEN


const token = process.env.TOKEN;
const clientId = process.env.CLIENTID;
const DATABASE_URL = process.env.DATABASE_URL;
const DATABASE_USER = process.env.DATABASE_USER;
const DATABASE_PASSWORD = process.env.DATABASE_PASSWORD;
const DATABASE_PORT = process.env.DATABASE_PORT;

ENV TZ=Asia/Seoul

WORKDIR /usr/app
COPY ./ ./
RUN npm install

CMD ["node", "main.js"]
