name: Build and Run Locally

on:
  push:
    branches-ignore:
      - "release"
  pull_request:
    branches-ignore:
      - "release"

jobs:
  build-and-run-locally:
    runs-on: [self-hosted, Linux, ARM64]

    env:
      TOKEN: ${{ secrets.TOKEN }}
      CLIENTID: ${{ secrets.CLIENTID }}
      GUILDID: ${{ secrets.GUILDID }}
      DATABASE_URL: ${{ secrets.DATABASE_URL }}
      NEISKEY: ${{ secrets.NEISKEY }}
      GITHUBTOKEN: ${{ secrets.GITHUBTOKEN }}

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: "20.9.0"

      - name: Build Docker Image
        run: |
          docker build --platform linux/arm64 \
            --network=host \
            --build-arg TOKEN=$TOKEN \
            --build-arg CLIENTID=$CLIENTID \
            --build-arg GUILDID=$GUILDID \
            --build-arg DATABASE_URL=$DATABASE_URL \
            --build-arg NEISKEY=$NEISKEY \
            --build-arg GITHUBTOKEN=$GITHUBTOKEN \
            --cache-from=pulled-image:tag \
            -t corn-bot:latest .

      - name: Run Locally
        run: docker run -d --name your-container-name corn-bot:latest
