name: development CI // 1

on: // 2
  push:
    branches-ignore:
      - "release"
  pull_request:
    branches-ignore:
      - "release"

defaults: // 3
  run:
    working-directory: ./discord-bot

jobs:
  node_CI:
    runs-on: ubuntu-latest // 4

    strategy: // 5
      matrix:
        node-version: [20.x]

    steps:
      - name: Checkout source code
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3 // 7
        with:
          node-version: ${{ matrix.node-version }}

      - name: Install dependencies
        run: npm i // 8

      - name: Run bot
        run: node main // 9
