name: Bot docker based CI

on:
  push:
    branches-ignore:
      - "release"
  pull_request:
    branches-ignore:
      - "release"

jobs:
  node_CI:
    runs-on: [self-hosted, Linux, ARM64]

    steps:
      - uses: actions/checkout@v3

      - name: Run Container
        run: docker compose up -d --build
        env:
          TOKEN: ${{ secrets.TOKEN }}
          CLIENTID: ${{ secrets.CLIENTID }}
          GUILDID: ${{ secrets.GUILDID }}
          DATABASE_URL: ${{ secrets.DATABASE_URL }}
          NEISKEY: ${{ secrets.NEISKEY }}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Cleanup Unused Images
        run: docker image prune -f
